#default
  seed: 1337    # -1 for random
  num_cpu: 6

#paths
  checkpoints_dir: models/model.pth
  logs_dir: ./
  train_dir: training/
  val_dir: val/

#model:
  nclasses: 2

#training:
  n_epochs: 10
  batch_size: 64
  lr: 0.001
  lr_stepsize: 7
  lr_gamma: 0.1
  momentum: 0.9